spring:
  application:
    name: jpaconsulta
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/Northwind
    username: postgres
    password: postgres
